food_app/accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('login/', CustomLoginView.as_view(), name='login'),
]

food_app/food_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),  # new
    path("accounts/", include("django.contrib.auth.urls")),  # new
    path("",include("sitepages.urls",namespace="sitepages")),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

food_app/sitepages/urls.py
from django.urls import path

from .views import *
app_name="sitepages"







urlpatterns = [
    path('',Home,name="homepage"),
    path('about/',About,name="aboutpage"),
    path('service/',Service,name="servicepage"),
    path('booking/',Booking,name="bookingpage"),
    path('team/',Team,name="teampage"),
    path('testimonial/',Testimonial,name="testimonialpage"),
    path('contact/',Contact,name="contactpage"),
    path('subscribe/',Subscribe,name="subscribe"),
    path('subscriptionconfirm/', subscription_confirm, name='subscriptionconfirm'),
    path('book_table/', book_table, name='book_table'),
    path('booking_success/', booking_success, name='bookingsuccess'),
    path('view_booking_history/', view_booking_history, name='view_booking_history'),
    path('details/<int:pid>',Details,name="details"),
    path('addtocart/<int:pid>',AddtoCart,name="addtocart"),
    path('deletefromcart/<int:pid>/', DeletefromCart, name='delete_from_cart'),
    path('order_history/', order_history, name='order_history'),
    path('viewcart/',ViewCart,name="viewcart"),
    path('removefromcart/<int:pid>',RemovefromCart,name="addtocart"),
    path('accounts/profile/', profile, name='profile'),
    path('dashboard/', dashboard, name='dashboard'),
    path('editprofile/', editprofile, name='editprofile'),
    path('profile/', viewprofile, name='profile'),
    path('checkout',checkout,name="checkout"),
    path('initiate_payment/<int:order_id>/<int:total_amount>/<str:email>/', initiate_payment, name='initiate_payment'),
    path('paystack-webhook/', paystack_webhook, name='paystack_webhook'),
    path('order_success/', order_success, name='order_success'),
    # path('payment_callback/', payment_callback, name='payment_callback'),
   
    # path('initiate_payment/<int:order_id>/', initiate_payment, name='initiate_payment'),
    # path('payment_callback/', payment_callback, name='payment_callback'),
    # path('order_success/', order_success_page, name='order_success_page'),
    # path('order_error/', order_error_page, name='order_error_page'),
    
    # path('paystack/callback/<int:order_id>/', paystack_callback, name='paystack_callback'),
    # path('orderhistory/', order_history, name='order_history'),
]

# Create your views here.

food_app/sitepages/forms.py
# forms.py
from django import forms
from .models import UserProfile




class CheckoutForm(forms.Form):
    full_name = forms.CharField(label='Full Name', max_length=255)
    email = forms.EmailField(label='Email')
    delivery_address = forms.CharField(label='Delivery Address', max_length=255)
    phone_number = forms.CharField(label='Phone Number', max_length=15)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'delivery_address', 'email', 'phone_number']

food_app/sitepages/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import FoodItem,Purchase,OrderItem,CheckoutDetails,UserProfile,Subscriber,ContactMessage
from django.db import transaction
from uuid import uuid4
import uuid 
import urllib.parse
#
from .forms import CheckoutForm,UserProfileForm

from django.contrib.auth.decorators import login_required

#
# from sitepages.forms import UserProfileForm

import hmac
import hashlib
import traceback  # Import traceback for detailed error logging
from urllib.parse import quote

from django.db.models import Max



from sitepages.models import Booking as MyAppBooking, Table as MyAppTable,BookingHistory
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponse
from django.utils import timezone
 


from decimal import Decimal
# # from paystackapi import Transaction
# from paystackapi.transaction import Transaction
# import paystack
import paystack
from django.http import JsonResponse



from datetime import datetime
from django.core.mail import send_mail,BadHeaderError
from django.core.validators import validate_email
from django.core.exceptions import ValidationError





from django.conf import settings
import time
import random
import logging
import requests
import json
from django.http import JsonResponse, HttpResponseNotAllowed
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, redirect
from django.core.mail import send_mail
from django.views.decorators.http import require_POST


logger = logging.getLogger(__name__)

# Create your views here.
def Home(request):
    if 'usercart' in request.session:
        x = request.session['usercart']
        totalnumber = len(x)
    else:
        request.session['usercart'] = []
        x = request.session['usercart']
        totalnumber = len(x)

    # Separate queries for breakfast, lunch, and dinner items
    breakfast_items = FoodItem.objects.filter(category='Breakfast')
    lunch_items = FoodItem.objects.filter(category='Lunch')
    dinner_items = FoodItem.objects.filter(category='Dinner')

    data = {
        "ptitle": "Meals order & bookings - Home page",
        "breakfast_items": breakfast_items,
        "lunch_items": lunch_items,
        "dinner_items": dinner_items,
        "ttl": totalnumber,
    }

    return render(request, "sitepages/home.html", data)


def About(request):
    data={"ptitle":"Meals order & bookings - About Us"}
    return render(request,"sitepages/about.html",data)
def Service(request):
    data={"ptitle":"Meals order & bookings - Service"}
    return render(request,"sitepages/service.html",data)
def Booking(request):
    data={"ptitle":"Meals order & bookings - Booking"}
    return render(request,"sitepages/booking.html",data)
def Team(request):
    data={"ptitle":"Meals order & bookings - Our Team"}
    return render(request,"sitepages/team.html",data)
def Testimonial(request):
    data={"ptitle":"Meals order & bookings - Testimonial"}
    return render(request,"sitepages/testimonial.html",data)
def Contact(request):
    
    if request.method == 'POST':
        message_name = request.POST['name']
        message_email = request.POST['email']
        message_subject = request.POST['subject']
        message_msg = request.POST['message']


        

        email_subject = f"{message_subject}"
        email_body = f"Sender Name: {message_name}\nSender Email: {message_email}\n\nMessage: {message_msg}"
        sender_email = message_email
        recipient_list = [settings.EMAIL_HOST_USER]

        send_mail(
            email_subject,
            email_body,
            sender_email,
            recipient_list,
            fail_silently=True
        )

         # Create an instance of ContactMessage model and save it to the database
        contact_message = ContactMessage.objects.create(
            name=message_name,
            email=message_email,
            subject=message_subject,
            message=message_msg
        )

        

        data={"ptitle":"Meals order & bookings - Contact Us","message_name": message_name}
        return render(request,"sitepages/contact.html",data)

    else:
        data={"ptitle":"Meals order & bookings - Contact Us"}
        return render(request,"sitepages/contact.html",data)
    return render(request,"sitepages/contact.html",data)
def Details(request,pid):
    x=request.session['usercart']
    print(len(x))
    mdata = FoodItem.objects.get(id=pid)
    data={"ptitle":"Meals order & bookings - Home page","mdata": mdata}
    return render(request,"sitepages/details.html",data)


def AddtoCart(request, pid):
    x = request.session['usercart']
    x.append(pid)
    request.session['usercart'] = x
    return redirect("/viewcart")

def RemovefromCart(request, pid):
    x = request.session['usercart']
    x.remove(pid)
    request.session['usercart'] = x
    return redirect("/viewcart")

def DeletefromCart(request, pid):
    x = request.session['usercart']
    
    # Remove all occurrences of the item from the cart
    while pid in x:
        x.remove(pid)
    
    request.session['usercart'] = x
    return redirect("/viewcart")


@login_required
def profile(request):
    data={"ptitle":"Meals order & bookings - User Profile"}
    return render(request, 'registration/profile.html',data)

@login_required
def dashboard(request):
    data={"ptitle":"Meals order & bookings - Dashboard"}
    return render(request, 'registration/dashboard.html',data)




@login_required
def editprofile(request):
    user_profile = request.user.userprofile
    

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('/profile')  # Redirect to the user's profile page
    else:
        form = UserProfileForm(instance=user_profile)
    

    return render(request, 'registration/editprofile.html', {'form': form})



@login_required
def viewprofile(request):
    user_profile = request.user.userprofile  # Assuming a one-to-one relationship between User and UserProfile
    

    return render(request, 'registration/profile.html', {'user_profile': user_profile,"ptitle":"Meals order & bookings - User Profile"})


def Subscribe(request):
    error_message = None
    success_message = None

    if request.method == 'POST':
        email = request.POST.get('email', '')

        # Perform email validation
        try:
            validate_email(email)
        except ValidationError:
            error_message = "Invalid email format. Please provide a valid email address."
        else:
            # Additional validation or processing here if needed

            # Save the email to the database (create a new Subscriber instance)
            subscriber, created = Subscriber.objects.get_or_create(email=email)

            # Custom logic for sending email when the form is valid
            subject = 'Thank you for subscribing'
            message = 'Welcome to Restoran where flavor meets delight! 🍽️ Get ready to embark on a culinary journey with us. As a valued member, you will enjoy exclusive offers, mouthwatering recipes, and delightful surprises delivered straight to your inbox. Lets savor the taste of good times together! 🎉✨'
            send_mail(subject, message, settings.EMAIL_HOST_USER, [email], fail_silently=True)

            success_message = f"Thank you for subscribing! An email has been sent to {email} for confirmation."

            # Redirect to subscriptionconfirm.html after successful form submission
            return render(request, 'sitepages/subscriptionconfirm.html', {'error_message': error_message, 'success_message': success_message})

    return render(request, 'sitepages/subscriptionconfirm.html', {'error_message': error_message, 'success_message': success_message})





def subscription_confirm(request):
    return render(request, 'sitepages/subscriptionconfirm.html')


@login_required
def book_table(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        datetime_str = request.POST.get('datetime')
        no_of_people = int(request.POST.get('select1'))
        message = request.POST.get('message')

        # Convert datetime string to a datetime object
        date_time_obj = datetime.strptime(datetime_str, '%m/%d/%Y %I:%M %p')

        
            # Try to get the table based on the selected type
        table =MyAppTable.objects.get(table_type=f'People {no_of_people}')

        # Get the authenticated user
        user = request.user

     
        

        # Calculate price based on the selected table type
        price = table.price
        send_confirmation_email(email,date_time_obj, no_of_people, message, price)

           # Create a Booking instance using create method
        booking = MyAppBooking.objects.create(
            user=user,
            table=table,
            booking_date=date_time_obj.date(),
            booking_time=date_time_obj.time(),
            message=message,
            payment_status='pending',  # Set initial payment status to pending
        )

        # Create a BookingHistory instance
        booking_history = BookingHistory.objects.create(
            user=user,
            booking=booking,
            payment_status='pending',  # Set initial payment status to pending
        )

        return redirect('/booking_success')

    return render(request, 'sitepages/booking.html')

def send_confirmation_email(user_email, booking_date, no_of_people, message, price):
    bank_name = "Opay Bank"
    subject = 'Booking Confirmation'
    message = f'Thank you for booking. Here are your booking details:\n\n' \
              f'Table Type: People {no_of_people}\n' \
              f'Date: {booking_date.date()}\n' \
              f'Time: {booking_date.time()}\n' \
              f'Price: {price}\n\n' \

food_app/templates/sitepages/booking_success.html
<!-- templates/registration/signup.html -->
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}
<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{ptite}}</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="/">Pages</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">Booking Success</li>
            </ol>
        </nav>
    </div>
</div>
</div>

<h2 style="text-align: center;">Your booking has been placed .....check your mail for a confirmation mail</h2>
{% endblock %}

food_app/templates/sitepages/checkout.html
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}
<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{ data.ptitle }}</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Pages</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">Checkout page</li>
            </ol>
        </nav>
    </div>
</div>
</div>
<style>
    /* body {
      font-family: 'Arial', sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      
    } */

    .checkout-form {
      background-color: #fff;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
      padding: 20px;
      width: 400px;
      text-align: left;
    }

    h1 {
      color: #333;
      text-align: center;
    }

    label {
      display: block;
      margin-bottom: 8px;
      color: #555;
    }

    input,
    textarea {
      width: 100%;
      padding: 10px;
      margin-bottom: 16px;
      box-sizing: border-box;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    input[type="submit"] {
      background-color: #4CAF50;
      color: #fff;
      border: none;
      padding: 12px 20px;
      border-radius: 5px;
      cursor: pointer;
    }

    input[type="submit"]:hover {
      background-color: #45a049;
    }

    .order-details-box {
    border: 1px solid #ccc;
    padding: 15px;
    margin: 20px;
    background-color: white;
    border-radius: 20px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    
 }
 .checkout-container {
        display: flex;
        justify-content: center;
        /* margin: 20px 100px; Adjust the margin as needed */
  }
  </style>


<h1>Checkout</h1>
<div class="checkout-container">
    <form class="checkout-form" method="post" action="{% url 'sitepages:checkout' %}">
        {% csrf_token %}

        <div id="checkoutDetailsSection">
            <h2>Checkout Details</h2>
            {{ form.as_p }}
        </div>

        <div class="order-details-box">
            <h2>Order Details</h2>
            <ul>
                {% for i in citems %}
                    <li>{{ i.name }} - Quantity: {{ i.qty }} - Unit Price: {{ i.u_price }} - Total: {{ i.uqty }}</li>
                {% endfor %}
            </ul>
        
            <p>Total Amount: &#8358; {{ totalsum }}</p>
            <p>Delivery Fee: &#8358; {{ delivery_fee }}</p>
            <h2>Total Amount (including Delivery Fee): &#8358; {{ totalsum|add:delivery_fee }}</h2>
        </div>

        <input type="submit" value="Proceed to Payment">
    </form>
</div>





  



  
 
   
    
  {% endblock %}
  



    
  
    
    
    


    

food_app/templates/sitepages/contact.html
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}

            <div class="container-xxl py-5 bg-dark hero-header mb-5">
                <div class="container text-center my-5 pt-5 pb-4">
                    <h1 class="display-3 text-white mb-3 animated slideInDown">{{ ptitle }}</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Contact</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Navbar & Hero End -->

  
        {% if message_name %}
        <div style="text-align: center;">
            <h2>Thanks {{message_name}}!</h2>
            <p>we've received your email and will respond shortly 👍</p>
        </div>
        {% else %}


        <!-- Contact Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h5 class="section-title ff-secondary text-center text-primary fw-normal">Contact Us</h5>
                    <h1 class="mb-5">Contact For Any Query</h1>
                </div>
                <div class="row g-4">
                    <div class="col-12">
                        <div class="row gy-4">
                            <div class="col-md-4">
                                <h5 class="section-title ff-secondary fw-normal text-start text-primary">Booking</h5>
                                <p><i class="fa fa-envelope-open text-primary me-2"></i>book@example.com</p>
                            </div>
                            <div class="col-md-4">
                                <h5 class="section-title ff-secondary fw-normal text-start text-primary">General</h5>
                                <p><i class="fa fa-envelope-open text-primary me-2"></i>info@example.com</p>
                            </div>
                            <div class="col-md-4">
                                <h5 class="section-title ff-secondary fw-normal text-start text-primary">Technical</h5>
                                <p><i class="fa fa-envelope-open text-primary me-2"></i>tech@example.com</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeIn" data-wow-delay="0.1s">
                        <iframe class="position-relative rounded w-100 h-100"
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                            frameborder="0" style="min-height: 350px; border:0;" allowfullscreen="" aria-hidden="false"
                            tabindex="0"></iframe>
                    </div>
                    <div class="col-md-6">
                        <div class="wow fadeInUp" data-wow-delay="0.2s">
                            <form action="{%url 'sitepages:contactpage' %}" method="POST">
                                {% csrf_token %}
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" id="name" name="name" placeholder="Your Name">
                                            <label for="name">Your Name</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input type="email" class="form-control" id="email" name="email" placeholder="Your Email">
                                            <label for="email">Your Email</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" id="subject" placeholder="Subject" name="subject">
                                            <label for="subject">Subject</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <textarea class="form-control" placeholder="Leave a message here" id="message" name="message" style="height: 150px"></textarea>
                                            <label for="message">Message</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <!-- Contact End -->

{%endblock%}

food_app/templates/sitepages/initiate_payment.html
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}
<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{pslug}}</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Pages</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">{{pslug}}</li>
            </ol>
        </nav>
    </div>
</div>
</div>








    <h1>Checkout Summary</h1>

    <h2>Order Details</h2>
    <ul>
        {% for i in citems %}
            <li>{{ i.name }} - Quantity: {{ i.qty }} - Unit Price: {{ i.u_price }} - Total: {{ i.uqty }}</li>
        {% endfor %}
    </ul>

    <h2>Total Amount: &#8358; {{ tsum }}</h2>
    <p>Delivery Fee: &#8358; {{ delivery_fee }}</p>
    <p>Total Amount (including Delivery Fee): &#8358; {{ tsum|add:delivery_fee }}</p>
    <p>{{total_amount}}</p>

    <h2>Delivery Information</h2>
    {% if user_profile %}
        <p>Name: {{ user_profile.first_name }} {{ user_profile.last_name }}</p>
        <p>Email: {{ user_profile.email }}</p>
        <p>Delivery Address: {{ user_profile.delivery_address }}</p>
        <p>Phone Number: {{ user_profile.phone_number }}</p>
    {% endif %}

    <form method="POST" action="{% url 'sitepages:initiate_payment' order_id=order.id %}">
        {% csrf_token %}
        <button type="submit">Proceed to Payment</button>
    </form>

    
    <a href="{% url 'sitepages:viewcart' %}">Back to Cart</a>







      

{%endblock%}

food_app/templates/sitepages/order_history.html
<!-- templates/registration/signup.html -->
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}
<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{ptite}}</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="/">Pages</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">Order history</li>
            </ol>
        </nav>
    </div>
</div>
</div>
<!-- order_history.html -->



  <h1>Your Order History</h1>

  {% if purchases %}
    <ul>
      {% for purchase in purchases %}
        <li>
          <strong>Order ID:</strong> {{ purchase.id }}<br>
          <strong>Status:</strong> {{ purchase.status }}<br>
          <strong>Total Amount Paid:</strong> {{ purchase.total_amount_paid }}<br>
          <strong>Order Date:</strong> {{ purchase.order_date }}<br>

          <h3>Ordered Items:</h3>
          <ul>
            {% for item in purchase.order_items.all %}
              <li>
                {{ item.quantity }} x {{ item.product_name }} - {{ item.total_price }}
              </li>
            {% endfor %}
          </ul>
        </li>
        <hr>
      {% endfor %}
    </ul>
  {% else %}
    <p>No order history available.</p>
  {% endif %}
{% endblock %}

food_app/templates/sitepages/order_success.html
<!-- templates/registration/signup.html -->
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}
<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{ptite}}</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="/">Pages</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">Order Successful</li>
            </ol>
        </nav>
    </div>
</div>
</div>

    <h2 style="text-align: center;">Your Order has been placed once we confirm your payment order will be shipped .....check your mail for a confirmation mail</h2>
<div style="display: flex;justify-content: center;">
    <img src="{%static 'img/delivery-bus.png' %}" alt="">

</div>
{% endblock %}

food_app/templates/sitepages/orderhistory.html
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}



            <div class="container-xxl py-5 bg-dark hero-header mb-5">
                <div class="container text-center my-5 pt-5 pb-4">
                    <h1 class="display-3 text-white mb-3 animated slideInDown">Cart</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="/">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Cart Details</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Navbar & Hero End -->
<!-- orderhistory.html -->


  <h1>Your Order History</h1>

  {% if orders %}
    <table>
      <thead>
        <tr>
          <th>Order ID</th>
          <th>Total Amount</th>
          <th>Payment Date</th>
          <!-- Add more columns as needed -->
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
          <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.total_amount }}</td>
            <td>{{ order.orderhistory.payment_date }}</td>
            <!-- Add more columns as needed -->
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No orders found.</p>
  {% endif %}






      

{%endblock%}

food_app/templates/sitepages/payment_failure.html
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}
<div class="container-xxl py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{pslug}}</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Pages</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">{{pslug}}</li>
            </ol>
        </nav>
    </div>
</div>
</div>

<h1>Payment not Successful</h1>
<p>Your payment hasn't been received go back and make your payment then your order will be successfully processed.</p>





      

{%endblock%}

food_app/templates/sitepages/subscriptionconfirm.html
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}

            <div class="container-xxl py-5 bg-dark hero-header mb-5">
                <div class="container text-center my-5 pt-5 pb-4">
                    <h1 class="display-3 text-white mb-3 animated slideInDown">Subscription Confirm</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="/">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Subscription Confirm</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Navbar & Hero End -->

        <!-- subscriptionconfirm.html -->



    <div style="text-align: center;">
        <h1>Subscription Confirmation</h1>

    {% if success_message %}
        <p style="color: green;">{{ success_message }} 👍</p>
    {% elif error_message %}
        <p style="color: red;">{{ error_message }} 😮</p>
    {% endif %}

    </div>






      
        

       
      {%endblock%}